name: Actions
on:
  pull_request: 
    branches: ["master", "develop"]
  workflow_dispatch:
jobs:
  build:
    name: Build without tests
    runs-on: ubuntu-latest
    steps:
      - name: Lintin
        run: npx prettier --write . 
