name: Actions
on:
    pull_request:
        branches: ['master', 'develop']
    workflow_dispatch:
jobs:
    build:
        name: Linting code
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
            - name: Install dependencies
              run: npm install
            - name: Lintin
              run: npx prettier --write src/
